### ISSUE TITLE
Error when compiling helloworld

### ISSUE THREAD

**Issue by TurBoss** [clydeshaffer/HelloGameTank_cc65#1]
Hello!

Nice project, I'm trying to get the hello-world to compile but I'm facing this issue on arch-linux with cc65-git

```
➜  HelloGameTank_cc65 git:(main) ✗ make
mkdir -p build
ca65 --cpu 65sc02 -o build/vectors.o src/vectors.s
mkdir -p build
ca65 --cpu 65sc02 -o build/wait.o src/wait.s
mkdir -p build
ca65 --cpu 65sc02 -o build/interrupt.o src/interrupt.s
mkdir -p build
cc65 -t none -O --cpu 65sc02 -o build/hello.si src/hello.c
mkdir -p build
ca65 --cpu 65sc02 -o build/hello.o build/hello.si
build/hello.si(12): Error: Cannot open include file 'longbranch.mac': No such file or directory
make: *** [Makefile:29: build/hello.o] Error 1
rm build/hello.si
➜  HelloGameTank_cc65 git:(main) ✗ 
```

I could not figure what is longbranch.mac or where it comes from :-)

thanks

**Comment by clydeshaffer** [comment]
Interesting, it should be available in the cc65 git repo under the asminc folder.
Can you check if it's there?
If it is present, then somehow cc65 is unable to find its own includes folder.

**Comment by clydeshaffer** [comment]
(Or rather **ca65** can't find its default includes)

**Comment by TurBoss** [comment]
ok found the issue

had an old version of cc65 in ~/.local/bin installed by me long ago and forgot

removed that and started working nicely

Thanks for you time ,super awesome project !!

 I'll try to write a Conway game of life
 
 thank you again!

**Comment by clydeshaffer** [comment]
Glad to hear it's working!
